# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: miles/backends/dynamo_utils/engine_state.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.miles/backends/dynamo_utils/engine_state.proto\x12\x0cmiles.dynamo\"2\n\tModelInfo\x12\x12\n\nmodel_path\x18\x01 \x01(\t\x12\x11\n\tjson_info\x18\x02 \x01(\t\"\x1f\n\nServerInfo\x12\x11\n\tjson_info\x18\x01 \x01(\t\"\xb3\x01\n\x0b\x45ngineState\x12\x13\n\x0binstance_id\x18\x01 \x01(\x04\x12\x10\n\x08revision\x18\x02 \x01(\x04\x12\x0f\n\x07healthy\x18\x03 \x01(\x08\x12\x10\n\x08is_pause\x18\x04 \x01(\x08\x12+\n\nmodel_info\x18\x05 \x01(\x0b\x32\x17.miles.dynamo.ModelInfo\x12-\n\x0bserver_info\x18\x06 \x01(\x0b\x32\x18.miles.dynamo.ServerInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'miles.backends.dynamo_utils.engine_state_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MODELINFO._serialized_start=64
  _MODELINFO._serialized_end=114
  _SERVERINFO._serialized_start=116
  _SERVERINFO._serialized_end=147
  _ENGINESTATE._serialized_start=150
  _ENGINESTATE._serialized_end=329
# @@protoc_insertion_point(module_scope)
